### ISSUE TITLE
MobileDoc node field return null

### ISSUE THREAD

**Issue by tomVlt** [TryGhost/gatsby-source-ghost#12]
Hi,

Each time I tried to query data post/pages through graphiql the mobiledoc field is set to null.
If I call the content api directly with a raw curl query it works fine, I've got data on mobiledoc format.

I installed the gatsby-source-ghost plugin localy and tried adding mobiledoc on postAndPageFetchOptions object's formats field. Located in gatsby-node.js, but this does not work.

`    const postAndPageFetchOptions = {
        limit: 'all',
        include: 'tags,authors',
        formats: 'mobiledoc,html,plaintext'
    };
`

Is there something I've missed ?

To go further, I thought it would be nice to have mobile doc format to add imageSharp processing support via a transformer plugin. There is a html-to-mobiledoc helper on the ghost SDK, but I don't think it's the right way to do it while at some point I should be able to query this format "natively".

![ghostnodegraphql](https://user-images.githubusercontent.com/38563184/51619815-63383f80-1f31-11e9-8195-92e0b4d097ed.PNG)

Hope someone can clarify.
Have a nice day

**Comment by tomVlt** [comment]
Meanwhile if found a workaround using the html-to-mobiledoc helper from the tryghost SDK.
I still need to implement the rejection on promise.

    const fetchPosts = api.posts.browse(postAndPageFetchOptions).then( async(posts) => {
    //Unescape HTML string & append a mobiledoc field to all posts nodes
      const addMobileDocField = posts => {
        return new Promise((res, rej) => {

          const postsData = posts.map(post => {
            let data = {};
            post.html = unescape(post.html);
            let mobiledoc = JSON.stringify(converter.toMobiledoc(post.html));
            let postWithMobileDoc = { ...post, mobiledoc };
            data = { ...data, ...postWithMobileDoc };
            return data;
          });

          res(postsData);
        })
      };

      // Workaround to inject mobiledoc field on each node | T<String>
      let transformedPostsData = await addMobileDocField(posts);
      transformedPostsData.forEach(post => createNode(PostNode(post)));
    });

    const fetchPages = api.pages.browse(postAndPageFetchOptions).then((pages) => {
        pages.forEach(page => createNode(PageNode(page)));
    });

Getting mobiledoc to work as a graphql field, type string

![graphqlmd](https://user-images.githubusercontent.com/38563184/51677859-3ccede80-1fdb-11e9-8559-e05073ebee2a.PNG)

I can now safely call React.CreateElement() on my unescaped mobiledoc JSON parsed object and work with it.
It is way more powerfull.
I'm now creating a transformer plugin to able image sharp on mobiledoc img url fields.
If there's no solution to query mobiledoc natively I can merge the previous code on the transformer plugin since Gatsby pattern is to not mutate data from source-plugins.

![console](https://user-images.githubusercontent.com/38563184/51678139-db5b3f80-1fdb-11e9-9fa2-c577c48bba74.PNG)

**Comment by tomVlt** [comment]
Ok then this is finaly working well.

I'm now able to generate a schema containing two new child Nodes for post and pages
- One called featureImg giving access to a file node containing feature_image file then discoverable by transformer-sharp
- The other called bodyImg giving access to all images inside a post/page body, it inject them as child files nodes again, then they are also discoverable by transformer-sharp

I've created a dummy post displaying pandas pictures from unsplash. Three random panda pictures in the body. The result in graphiql :

![source-ghost-gql](https://user-images.githubusercontent.com/38563184/51910046-5fdc0280-23ce-11e9-9315-3aa8b90f8b1e.png)

![source-ghost-gql-results](https://user-images.githubusercontent.com/38563184/51910070-68343d80-23ce-11e9-85ff-f187da15ab74.PNG)

I will implement the cache during the week.

I will then publish the source code on my profile since I had to refactor the whole plugin... Long story coming from current limitations when generating a schema using Gatsby helpers functions to create Nodes. The core logic behind the API is so complex that even the folks at Gatsby said it would take a large amount of investigation/time to refactor. To properly achieve what you see above, there's no other way than hard code Nodes logic almost everywhere, like gatsby-source-wordpress is done. Leading to the incompatibility with the current source code in the ghost-plugin.

After publishing I will close this issue as I found why mobiledoc field is not available (it's a ghost problem, it inherits directly from the content api).

Cheers

**Comment by kevinansfield** [comment]
> I found why mobiledoc field is not available (it's a ghost problem, it inherits directly from the content api)

This is by design, there shouldn't be any need for accessing the mobiledoc directly via the Content API. If you're looking to grab images from the post content then you're better off using the `html` field as it will be more reliable, there are multiple ways to add images to a post outside of image cards.

**Comment by tomVlt** [comment]
@kevinansfield Thank you for your response ! Okay I undestand. Content-api docs still mention it this is why I wondered about it.

I undestand your point of view with html. Ghost isn't build with the design of headless cms since it uses handlebar natively. But still, it exposes all the functionnality to do it ! I like handlebar, but compared to gatsby I think we all agree there's a huge gap of performance. This is the purpose of this plugin, leverage of all gatsby awesome features, including image sharp.

> you're better off using the html field as it will be more reliable

Reliable isn't the word according to me, I would say effortless...
And then I would have to parse html string to get my img tags back at query time ?

Yet I'm really curious about that. If you have time to give further explanations, maybe I've missed something :

> there are multiple ways to add images to a post outside of image cards.

Have a nice day.

**Comment by kevinansfield** [comment]
> Ghost isn't build with the design of headless cms since it uses handlebar natively.

Use of handlebars is irrelevant here, the Content API gives you what's needed whether you're using handlebars or a different templating library or static site generator. The `mobiledoc` field is an internal implementation detail.

> And then I would have to parse html string to get my img tags back at query time ?

Yes, if you need to extract content from or modify the output you should be parsing the `html` field. The `html` field will have the full content available in a single, well-understood, and easily parsable format. If you try to use the `mobiledoc` field then you also need libraries for the different cards, you'd need to parse markdown from the markdown cards to extract images from those for example (and a _lot_ of Ghost content uses markdown cards as that was the upgrade path from <2.0).

> there are multiple ways to add images to a post outside of image cards.

Markdown cards are one example that I mentioned above, there are also gallery cards, and embed cards and likely more (+ custom) cards in the future. Ghost has the knowledge built-in to render the content of those cards and that content is stored in the `html` field making it the source of truth for things like image extract.

**Comment by tomVlt** [comment]
@kevinansfield thanks a lot for your time and for those explanations. I will go this way then.

Need just a bit logic to insert gatsby img component to replace native html img tags, but I get the idea. Shouldn't be difficult.

Can't wait to see custom cards in the future :)

I think we can close this issue.
Regards,
