### ISSUE TITLE
403 on default author profile picture

### ISSUE THREAD

**Issue by riencoertjens** [TryGhost/gatsby-source-ghost#19]
### Issue Summary

we're getting a build failing with following error, this happens only on our online builds, not locally
```
success onPreBootstrap - 0.010s
error "gatsby-node.js" threw an error while running the onCreateNode lifecycle:
failed to process https://casper.ghost.org/v2.0.0/images/ghost.png
HTTPError: Response code 403 (Forbidden)
```

the url can be found here: https://github.com/TryGhost/gatsby-source-ghost/blob/master/ghost-schema.js#L18

changing the url to a publicly accessible one fixes the issue, so maybe you guys need to change some accessibility settings for this particular url?

**Comment by kevinansfield** [comment]
@riencoertjens the image is publicly accessible but it's possible your external build machine's IP addresses were blocked for some reason.

If you are having trouble you can always replace the dummy/demo data with your own data which it sounds like you've done.

**Comment by gurpreetatwal** [comment]
Might be a silly question, but what's the easiest way to replace the demo data without forking the repo and editing it?
