### ISSUE TITLE
Update gatsby-source-ghost plugin to support Gatsby 5 and Node 18.x

### ISSUE THREAD

**Issue by ThanosDi** [TryGhost/gatsby-source-ghost#250]
### Issue Summary

It seems that we are unable to update to the new Gatsby version 5 as `gatsby-source-ghost` requires a node version 16.x but Gatsby requires Node version 18.x
When trying to update Gatsy to version 5 we get the following:
```
$ yarn add gatsby
error gatsby-core-utils@4.0.0: The engine "node" is incompatible with this module. Expected version ">=18.0.0". Got "16.16.0"
error Found incompatible module.
```
And after updating node version to >=18.0.0 we get the following
```
error gatsby-source-ghost@5.0.0: The engine "node" is incompatible with this module. Expected version "12.x || 14.x || 16.x". Got "18.7.0"
error Found incompatible module.
```

### To Reproduce

1. Install Gatsby version 5 npm package
2. Install gatsby-source-ghost npm package

### Technical details:

* Ghost Version: 5
* Gatsby Version: 5.0.1
* Gatsby Source Ghost Version: 5.0.0
* Node Version: 18.7.0
* OS: Ubuntu

**Comment by michailbrynard** [comment]
This is also a blocker for us for upgrading to Gatsby 5. I see there is a pull request that fixes that issue: https://github.com/TryGhost/gatsby-source-ghost/pull/247

@aileen Would it be possible for you to merge the above PR and release a new version?

**Comment by aileen** [comment]
Done with https://github.com/TryGhost/gatsby-source-ghost/commit/0649f8863c1a0b5791eaf05570ba2a8fd039ce12
