### ISSUE TITLE
allGhostPage not working

### ISSUE THREAD

**Issue by HeikoMueller** [TryGhost/gatsby-source-ghost#3]
Hi,

while trying to build queries, I only see allGhostPost, allGhostAuthor and allGhostTag working. allGhostPage does not appear in the GraphiQL dropdown list. Also copy/pasting the query does not work:

{
  "errors": [
    {
      "message": "Cannot query field \"allGhostPage\" on type \"Query\". Did you mean \"allGhostTag\", \"allGhostPost\", \"allSitePage\", \"ghostTag\", or \"allGhostAuthor\"?",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}

Is this a feature or a bug ? 

Best
Heiko

**Comment by HeikoMueller** [comment]
The error seems to be caused by cached site data, requesting allGhostPage works fine after having restarted gatsby.

**Comment by Mushu62** [comment]
Hi @HeikoMueller ,

I'm facing the same issue and I restarted Gatsby with no success.

Do you have another solution?

**Comment by AileenCGN** [comment]
In order to have `allGhostPages` populated you will have to have pages in Ghost itself. I know, this is a stupid question, but do you have pages in your Ghost Admin? Clearing the cache otherwise is usually very helpful as well. My favourite command: `gatsby clean`

**Comment by Mushu62** [comment]
Hi @AileenCGN , thank you so much for your quick reply. I haven't created any pages yet, so the admin page displays none.

**Comment by AileenCGN** [comment]
Yeah, so Gatsby creates the GraphQL schema based on the content it finds. If nothing is there, the source will not be created. As soon as you publish a page in Ghost, you should be able to query it with GraphQL as well as `allGhostPages`, just like you can with posts.
