### ISSUE TITLE
Gatsby fails to build when site meta settings are unset.

### ISSUE THREAD

**Issue by WillTheVideoMan** [TryGhost/gatsby-source-ghost#42]
### Issue Summary

Gatsby fails to build when site meta settings are unset. Meta fields are not included in the schema when no value is assigned in Ghost, causing Gatsby build error. 

### To Reproduce

1. Populate the Ghost site meta settings (meta/og/twitter title/description/image).
2. In Gatsby, construct a GraphQL Query as such:
``` GraphQL
query {
  ghostSettings {
    og_description
    og_image
    og_title
    meta_description
    meta_title
    twitter_description
    twitter_image
    twitter_title
  }
}
```
3. The query successfully returns the set site meta settings at build-time. 
4. Now, unset the site meta settings in Ghost. 
5. Attempt to rebuild Gatsby, and the following error is returned for each of the above fields:
```
ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "og_description" on type "GhostSettings".

If you don't expect "og_description" to exist on the type "GhostSettings" it is most likely a typo.
However, if you expect "og_description" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "og_description" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "GhostSettings":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions
```

#### Expected

Instead of the field disappearing from the schema, it should be set to `null` if unset. 

#### Observed

The aforementioned fields are not presented in the schema, causing build failure. 

### Technical details:

* Ghost Version: 3.13.4
* Gatsby Version: 2.11.17
* Gatsby Source Ghost Version: 4.0.4
* Node Version: v12.16.1
* OS: Elementary OS 5.1.3 Hera

### Discussion

Not sure whether I should be including catch logic on my side, but when other fields are unset in Ghost, `null` is returned as expected.

My hunch is that a fake nodes are not being set for the above fields, and that the file `ghost-schema.js` should be updated to include these fields in the settings object. 

https://github.com/TryGhost/gatsby-source-ghost/blob/d9be2458e4ab9ca2f6a31725c1d9577fde41b1d6/ghost-schema.js#L106-L125

From experimentation, all the above fields which have keys in the object are returned as `null` when unset, but the keys not present (but listed in the Ghost V3 API spec) are missing from the schema. 

It could be that I'm missing the point of this dummy schema, or that more is involved here, but it seems a sensible first guess. Please do let me know if I'm making some easy peasy mistakes here.

Cheers! 😊

**Comment by aileen** [comment]
The reason for this solution was definitely because of GraphQL issues with empty fields as described [here](https://github.com/gatsbyjs/gatsby/issues/10856#issuecomment-451701011). I can see there's a better recommended approach now in that referenced issue, which you already submitted as PR. This is super cool 🙏

I just updated the schema tho to now reflect the current status of what the API actually returns (a few properties were missing).

**Comment by WillTheVideoMan** [comment]
Hey @aileen! That's great to hear, I will be sure to work on the PR to bring it up to spec. Thanks too for catching those missing fields too; they so often slip under the radar.

Looking forward to getting this merged!
