### ISSUE TITLE
Fails with Gatsby schema rebuilding

### ISSUE THREAD

**Issue by vladar** [TryGhost/gatsby-source-ghost#44]
### Issue Summary

We've discovered recently that `gatsby-source-ghost` doesn't work with Gatsby schema rebuilding.

Full explanation on why this is happening: https://github.com/gatsbyjs/gatsby/issues/23633#issuecomment-622058800

The solution is to use Gatsby [schema customization API](https://www.gatsbyjs.org/docs/schema-customization/) to define schema instead of using "fake" objects.

### To Reproduce

```
$ git clone -b issue-gatsby-23633 https://github.com/styxlab/gatsby-starter-try-ghost.git
$ cd gatsby-starter-try-ghost
$ yarn
$ gatsby develop
```

### Technical details:

* Gatsby Version: 2.21.3
* Gatsby Source Ghost Version: 4.0.4

**Comment by aileen** [comment]
Merged with #61
