### ISSUE TITLE
Fails when Gatsby /__refresh is hit

### ISSUE THREAD

**Issue by koussay-khelil** [TryGhost/gatsby-source-ghost#46]
### Issue Summary

After using the /__refresh of Gatsby to make the content more dynamic the following message keeps appearing 

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "icon" on type "GhostSettings".

### To Reproduce

1. Activate the refresh endpoint of Gatsby
2. use the curl -X POST http://localhost:8000/__refresh
It is expected to rerun normally but it fails and sometimes even breaks
### Technical details:

* Ghost Version: V3
* Gatsby Version: 2.21.19
* Gatsby Source Ghost Version: 4.0.4
* Node Version: 12.13.1
* OS:Windows 10 x64

**Comment by daviddarnes** [comment]
Have you set the site icon in Ghost admin?

**Comment by koussay-khelil** [comment]
Yes I did

**Comment by aileen** [comment]
Is this still an issue? Is https://github.com/TryGhost/gatsby-source-ghost/issues/44 referring to the same issue?

**Comment by aileen** [comment]
I'm not able to reproduce this. This issue should also be resolved w/ #61. Please let me know if it still occurs, and we can re-open this issue.
