### ISSUE TITLE
Intermittent error during build, Cannot read property 'map' of undefined on posts

### ISSUE THREAD

**Issue by schpet** [TryGhost/gatsby-source-ghost#75]
### Issue Summary

seeing intermittent issue with gatsby-source-ghost and ghost pro:

```
1:43:10 PM: Fetch Contentful data: 8649.430ms
1:43:19 PM: error "gatsby-source-ghost" threw an error while running the sourceNodes lifecycle:
1:43:19 PM: Cannot read property 'map' of undefined
1:43:19 PM:   29 | 
1:43:19 PM:   30 | const transformCodeinjection = (posts) => {
1:43:19 PM: > 31 |     posts.map((post) => {
1:43:19 PM:      |           ^
1:43:19 PM:   32 |         const allCodeinjections = [post.codeinjection_head, post.codeinjection_foot].join('');
1:43:19 PM:   33 | 
1:43:19 PM:   34 |         if (!allCodeinjections) {
1:43:19 PM: 
1:43:19 PM: 
1:43:19 PM:   TypeError: Cannot read property 'map' of undefined
1:43:19 PM:   
1:43:19 PM:   - gatsby-node.js:31 transformCodeinjection
1:43:19 PM:     [repo]/[gatsby-source-ghost]/gatsby-node.js:31:11
1:43:19 PM:   
1:43:19 PM:   - gatsby-node.js:71 api.posts.browse.then
1:43:19 PM:     [repo]/[gatsby-source-ghost]/gatsby-node.js:71:17
1:43:19 PM:   
1:43:19 PM:   - next_tick.js:68 process._tickCallback
1:43:19 PM:     internal/process/next_tick.js:68:7
1:43:19 PM:   
1:43:19 PM: 
1:43:19 PM: not finished source and transform nodes - 17.225s
1:43:19 PM: ​
1:43:19 PM: ┌─────────────────────────────┐
1:43:19 PM: │   "build.command" failed    │
1:43:19 PM: └─────────────────────────────┘
```

### To Reproduce

don't have clear reproduce instructions, but it's a basic blog and a gatsby setup based off of 
 https://github.com/TryGhost/gatsby-starter-ghost

### Technical details:

* Ghost Version: Version 3.33.0
* Gatsby Version: gatsby@2.23.3
* Gatsby Source Ghost Version: gatsby-source-ghost@4.0.6
* Node Version: whatever netlify runs by default
* OS: whatever netlify runs by default

**Comment by schpet** [comment]
we've seen this problem on and off for months, but today I'm seeing it a lot. my guess is that the api response is not successful, and that gatsby-source-ghost doesn't handle this scenario gracefully. we'd like to continue using ghost pro but this behavior breaks our builds often.

**Comment by aileen** [comment]
What you're describing doesn't sound like a bug within this module. However, the handling of an empty API response should definitely be improved to deal with empty responses more gracefully.

**Comment by schpet** [comment]
thanks for checking this out @aileen! wondering where this bug exists, do you think it's in @tryghost/content-api ?

i'd expect `posts` here to always be an array of posts, and never undefined, but seems like `posts` is undefined here:

https://github.com/TryGhost/gatsby-source-ghost/blob/0c978545e06b92f624c6922e8bde3fabf9e6e04f/gatsby-node.js#L70-L73
