### ISSUE TITLE
Status undefined

### ISSUE THREAD

**Issue by SwampDolphin97** [TryGhost/gatsby-source-ghost#83]
This is working fine in my local machine but not on the server when I'm trying to gatsby build via docker image. 

DockerFile
FROM node:latest
RUN mkdir -p /koders-website
WORKDIR /koders-website
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json .
RUN npm install
RUN npm install --global gatsby-cli
COPY . .
EXPOSE 9000
RUN gatsby build
CMD ["gatsby", "serve", "-H", "0.0.0.0"]

My ghost docker container is running fine on http://161.97.112.22:2368

**GETS STUCK AT BUILDING**                                  
Shows this error
![image](https://user-images.githubusercontent.com/27912312/96154710-bc79ab00-0f2c-11eb-8caf-67429865a3ba.png)

**Comment by dispalt** [comment]
I mentioned in the commit as a comment, but I don't think ad02e4d fixes the error, it actually hides it.  I am getting it on a build machine, not sure if it's alpine or something related.
