### ISSUE TITLE
Cannot query field "ghostId" on type "GhostPost"

### ISSUE THREAD

**Issue by SwampDolphin97** [TryGhost/gatsby-source-ghost#84]
Unable to run my website using gatsby and ghost

Running Ghost container:
`curl http://161.97.112.22:2368`

Dockerfile: 
FROM node:latest
RUN mkdir -p /koders-website
WORKDIR /koders-website
COPY package.json .
RUN npm install
ENV PATH /app/node_modules/.bin:$PATH
RUN npm install --global gatsby-cli
COPY . .
EXPOSE 9000
RUN gatsby build
CMD ["gatsby", "serve", "-H", "0.0.0.0"]

Gatsby config:
{
      resolve: `gatsby-source-ghost`,
      options: {
         apiUrl: `http://0.0.0.0:2368`, //Tried 127.0.0.1:2368/localhost:2368/161.97.112.22:2368
        contentApiKey: `xxxxxxxxxxxxxxxxxxxxxxxxxx`,
      },
},
![image](https://user-images.githubusercontent.com/27912312/96194438-f9af5e80-0f67-11eb-8672-5b92050201fc.png)
![image](https://user-images.githubusercontent.com/27912312/96195188-c241b180-0f69-11eb-8374-03bb15d36db6.png)

**Comment by aileen** [comment]
Hey @SwampDolphin97 `ghostID` is not a property that exists in the Ghost Content API. You need to change that to `id` or `uuid`. I recommend checking out the [Gatsby Starter Ghost](https://github.com/TryGhost/gatsby-starter-ghost/) to see it in action.
